spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true



info:
  app:
    version: @project.version@
    author: lenu
    description: This is a multiuser anki training system