spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,logfile
  endpoint:
    health:
      show-details: always
  info:
    # Включает информацию о приложении из application.yml
    env:
      enabled: true
    # Включает информацию о git, собранную плагином
    git:
      mode: "full"

info:
  app:
    version: @project.version@
    author: lenu
    description: This is a multiuser anki training system